In [1]:
import numpy as np
import operator 
import kNN

groups,labels = kNN.createDataSet()

print(groups)
print(labels)

[[ 1.   1.1]
 [ 1.   1. ]
 [ 0.   0. ]
 [ 0.   0.1]]
['A', 'A', 'B', 'B']


In [10]:
np.tile([0,0],(groups.shape[0],1)) - groups

array([[-1. , -1.1],
       [-1. , -1. ],
       [ 0. ,  0. ],
       [ 0. , -0.1]])

In [5]:
(groups.shape[0],1)

(4, 1)

In [7]:
np.tile(30,(4,2))

array([[30, 30],
       [30, 30],
       [30, 30],
       [30, 30]])

In [12]:
a = np.random.rand(5)

In [13]:
a.argsort()

array([0, 3, 4, 2, 1])

In [14]:
import numpy as np
import operator 
import kNN

groups,labels = kNN.createDataSet()

print(groups)
print(labels)


[[ 1.   1.1]
 [ 1.   1. ]
 [ 0.   0. ]
 [ 0.   0.1]]
['A', 'A', 'B', 'B']


In [16]:
inX = [0,0];
dataSet = groups
dataSetSize = dataSet.shape[0];
diffMat = np.tile(inX,(dataSetSize,1)) - dataSet 

In [19]:
sqDiffMat = diffMat**2 
sqDistances = sqDiffMat.sum(axis = 1)

In [22]:
distances = sqDistances**0.5
sortedDistIndicies = distances.argsort()
sortedDistIndicies

array([2, 3, 1, 0])

In [29]:
classCount = {}
for i in range(3):
    voteIlabel  = labels[sortedDistIndicies[i]]
    classCount[voteIlabel] = classCount.get(voteIlabel,0) +1 

classCount   

{'A': 1, 'B': 2}

In [33]:
classCount = {}
for i in range(3):
    voteIlabel  = labels[sortedDistIndicies[i]]
    classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.iteritems(),key = operator.itemgetter(1),reverse = True)
    